#!/usr/bin/env bash
# Bash script that configures a new Ubuntu machine nginx

sudo apt update
sudo apt install nginx -y
ufw allow  'Nginx HTTP'
echo "Holberton School" > /etc/nginx/html/index.html
service nginx restart
