#!/usr/bin/env bash
# Configuring  Nginx server so that /redirect_me is redirecting to another page.

apt-get -y update
apt-get -y install nginx
ufw allow  'Nginx HTTP'
echo "Holberton School" > /var/www/html/index.html
sed -i '/listen 80 default_server;/a rewrite ^/redirect_me https://treasureglobalconcept.com.ng/ permanent;' /etc/nginx/sites-available/default 
service nginx restart
