#!/usr/bin/env bash
# Configuring Nginx server to have a custom 404 page
# Containing the string Ceci n'est pas une page.

apt-get -y update
apt-get -y install nginx
ufw allow  'Nginx HTTP' #nginx should be listed on port 80
echo 'Holberton School' > /etc/nginx/html/index.html
echo "Ceci n'est pas une page" > /etc/nginx/html/error404.html
printf %s "server {
    listen 80;
    listen [::]:80 default_server;
    root   /etc/nginx/html;
    index  index.html;

    location /redirect_me {
        return 301 https://treasureglobalconcept.com.ng/;
    }

    error_page 404 /error404.html;
    location /error404 {
      root /etc/nginx/html;
      internal;
    }
}" > /etc/nginx/sites-available/default

service nginx restart
