#!/usr/bin/env bash
# Configuring Nginx server to have a custom 404 page
# Containing the string Ceci n'est pas une page

apt-get -y update
apt-get -y install nginx
echo "Holberton School" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/error404.html
sed -i '/^\tserver_name.*/a error_page 404 /error404.html;\nlocation = /error404.html {\nroot /var/www/html/;\ninternal;\n}' /etc/nginx/sites-available/default
service nginx restart
